"""
Simulates a simple model of a colloidal suspension drying on a flexible cantilever.
The stress in the packed solid is assumed to be due to the Darcy (pore)
pressure generated by the interstitial fluid.  The code here only simulates
Stage (i) of drying.
"""

import numpy as np
from scipy.integrate import solve_ivp, cumulative_trapezoid
from params import Params
import matplotlib.pyplot as plt
from math import pi

plt.rcParams.update({
    "font.size": 16,
    "figure.autolayout": True
    })


def V_e(x):
    """
    Evaporation rate
    """

    a = 0.42714138
    b = -0.3028127

    c = pi * a + b
    return 1 / c * (2 * a / np.sqrt(1 - x**2) + b)

def q_p(x):
    """
    Flux from the packed region
    """

    a = 0.42714138
    b = -0.3028127

    c = pi * a + b

    return -(2 * a * np.arcsin(x) - pi * a + b * x - b) / c

def h_0(x, pars):
    """
    Initial film thickness
    """
    p = 1 / (1 - 1 / np.cosh(pars.Bond**(1/2)))
    return p * (1 - np.cosh(pars.Bond**(1/2) * x) / np.cosh(pars.Bond**(1/2)))

def x_p_ode(t, x_p, pars):
    """
    ODE for x_p
    """
    J_p = pars.phi_0 / pars.phi_p

    return -q_p(x_p) / ((1 - J_p) * h_0(x_p, pars) - V_e(x_p) * t)

def solve_x_p(t_span, x_p_0, pars):
    """
    Solves for the position of the packing front
    """

    sol = solve_ivp(x_p_ode, t_span, [x_p_0], args = (pars, ), atol = 1e-12, rtol = 1e-12)

    return sol

def compute_w_pre(t, x_p, pars):
    """
    Computes the deflection before t_g_salt
    """

    Nt = len(t)
    w_all = np.zeros_like(t)

    for n in range(len(t)):

        X, H, Sigma = compute_pre_quantities(t[n], x_p[n], pars)

        X /= 2
        w_x = cumulative_trapezoid(pars.E / 2 * H * (1 + pars.alpha * H) * Sigma, X, initial=0)
        w = cumulative_trapezoid(w_x, X, initial=0)

        w_all[n] = w[-1]

    return w_all

def compute_pre_quantities(t, x_p, pars):
    """
    Computes the solid/fluid regions, solid/fluid thickness, and
    solid/fluid stress before the salt-induced gelation time
    """

    N = 1000
    xi = np.linspace(0, 1-1e-8, N)

    X_f = xi * x_p
    X_p = x_p + (1 - x_p) * xi

    # height of packed film
    h_p = pars.phi_0 / pars.phi_p * h_0(X_p, pars)

    # compute pressure
    k_p = pars.a**2 / 45 * (1 - pars.phi_p)**3 / pars.phi_p**2
    p_scale = pars.V_e * (pars.L/2)**2 * pars.mu_f / k_p / pars.h_f

    p_0 = 0
    p = p_0 + p_scale / pars.G_0 * cumulative_trapezoid(-q_p(X_p) / h_p, X_p, initial=0)

    # compute solid stress
    sigma_f = -(1 - 2 * pars.nu_p) / (1 - pars.nu_p) * p

    X = np.r_[-X_p[::-1], -X_f[::-1], X_f, X_p]
    H = np.r_[
        h_p[::-1],
        h_0(-X_f[::-1], pars) - V_e(-X_f[::-1]) * t,
        h_0(X_f, pars) - V_e(X_f) * t,
        h_p
    ]

    Sigma = np.r_[
        sigma_f[::-1], 
        np.zeros(2*N), 
        sigma_f
    ]

    return X, H, Sigma



def main():
    """
    Solve the model and plot the deflection and solidification front
    """

    fig_w, ax_w = plt.subplots()
    fig_x, ax_x = plt.subplots()

    # loop over RH values
    for rh in [20, 40, 60, 80]:

        # create params assuming c_s = 1 M
        pars = Params(rh)

        # turn off the stress in the central colloidal gel after t_g_s
        # pars.incremental = 0

        # solve pre-gelation model
        sol_pre = solve_x_p((0, pars.t_end), 1-1e-6, pars)
        w_pre = compute_w_pre(sol_pre.t, sol_pre.y[0], pars)

        t_all = np.r_[sol_pre.t]
        w_all = np.r_[w_pre]
        x_p_all = np.r_[sol_pre.y[0]]

        """
        make some plots
        """

        # deflection
        plot = ax_w.plot
        p = plot(t_all, w_all, lw = 2, label = f'RH = {rh}')
        ax_w.set_xlabel('$t / t_d$')
        ax_w.set_ylabel('$\Delta w / h_s$')
        ax_w.legend()
        ax_w.set_ylim((0, 20))

        # packing front
        ax_x.plot(t_all, x_p_all, lw = 2, label = f'RH = {rh}', c =p[0].get_color())
        ax_x.legend()
        ax_x.set_xlabel('$t / t_d$')
        ax_x.set_ylabel('$x_p / L$')

    
    plt.show()

main()